// STUDENTS

export const GET_STUDENTS = "GET_STUDENTS";
export const ADD_STUDENT = "ADD_STUDENT";
export const REMOVE_STUDENT = "REMOVE_STUDENT";

// SINGLE STUDENT

export const GET_STUDENT = "GET_STUDENT";
export const EDIT_STUDENT = "EDIT_STUDENT";

// CAMPUSES

export const GET_CAMPUSES = "GET_CAMPUSES";
export const ADD_CAMPUS = "ADD_CAMPUS";
export const DELETE_CAMPUS = "DELETE_CAMPUS";

// SINGLE CAMPUS

export const SEARCH_CAMPUS = "SEARCH_CAMPUS";
export const EDIT_CAMPUS = "EDIT_CAMPUS";
